name: Receive Event

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update Assets
        run: python main.py
        env:
          WEBHOOK_TOKEN: ${{ toJson(github.event.client_payload) }}  # https://github.com/actions/runner/issues/475#issuecomment-1435491536
